/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ClinicSystem;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anas
 */
public class Appointment extends javax.swing.JFrame {

    Connection con = null;
    Statement stmt = null;
    ResultSet res = null; 
    
    /**
     * Creates new form Appointment
     */
    public Appointment() {
        initComponents();
        
        //For DataBase :
    try {
            
      con = DriverManager.getConnection("jdbc:derby://localhost:1527/FinalProjectDB","db","123");
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        // 1. Get the size of the PANEL, not the whole form
    int pWidth = jPanel1.getWidth();
    int pHeight = jPanel1.getHeight();

    // 2. Load your medical image
    ImageIcon icon = new ImageIcon(getClass().getResource("/Images/sidePanel.png"));

    // 3. Scale it to the PANEL's dimensions
    Image img = icon.getImage().getScaledInstance(pWidth, pHeight, Image.SCALE_SMOOTH);

    // 4. Apply it to the label and ensure the label fills the panel
    panelImg.setIcon(new ImageIcon(img));
    panelImg.setBounds(0, 0, pWidth, pHeight);
    
    //Exit btn design 
    btnExit.setBackground(new Color(255, 102, 102)); // Modern soft red
    btnExit.setForeground(Color.WHITE);
    btnExit.setFocusPainted(false);
    btnExit.setBorderPainted(false);
    
    // Search btn design
    btnSearch.setBackground(new Color(0, 102, 204));
    btnSearch.setForeground(Color.WHITE);
    
    //add btn design 
    btnInsert.setBackground(new Color(46, 204, 113));
    btnInsert.setForeground(Color.WHITE);
    btnInsert.setFont(new Font("Segoe UI", 1, 18));
    
    //delete btn design
    btnDelete.setFont(new Font("Segoe UI", 1, 18));
    btnDelete.setBackground(new Color(231, 76, 60));
    btnDelete.setForeground(Color.WHITE);
    
    }
    
    public void readData(){
    
        try {
         stmt = con.createStatement();
         res = stmt.executeQuery("SELECT * FROM DB.APPINTMENT");
    
        // 1. Get the Model and CLEAR it first so you don't get duplicates
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        model.setRowCount(0); 
    
        while (res.next()) {
           // 2. Get data from the database
           int aptId = res.getInt("apmtId");
           String patName = res.getString("patientName");
           String Gender = res.getString("Gender");
           java.sql.Date date = res.getDate("date");
           String status = res.getString("status");

           // 3. Add a NEW row to the table with the data
           model.addRow(new Object[]{aptId, patName, Gender, date, status});
       }
    
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Read Error: " + e.getMessage());
    }
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by theS Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupMF = new javax.swing.ButtonGroup();
        rdbGroupFinAct = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        btnApmt = new javax.swing.JButton();
        btnPatient = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        btnIntern = new javax.swing.JButton();
        panelImg = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPtName = new javax.swing.JTextField();
        txtAptId = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rdbMale = new javax.swing.JRadioButton();
        rdbFemale = new javax.swing.JRadioButton();
        rdbAct = new javax.swing.JRadioButton();
        rdbFin = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        txtRest = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnRest = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Appointment ID", "Patient Name", "Gender", "Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 700, 350));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 260, -1));

        btnApmt.setBackground(new java.awt.Color(255, 255, 255));
        btnApmt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnApmt.setText("Appointment");
        btnApmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApmtActionPerformed(evt);
            }
        });
        jPanel1.add(btnApmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 260, -1));

        btnPatient.setBackground(new java.awt.Color(255, 255, 255));
        btnPatient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPatient.setText("Patient");
        btnPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientActionPerformed(evt);
            }
        });
        jPanel1.add(btnPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 260, -1));

        txtSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 260, 30));

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 260, -1));

        btnIntern.setBackground(new java.awt.Color(255, 255, 255));
        btnIntern.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnIntern.setText("InternShips");
        btnIntern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInternActionPerformed(evt);
            }
        });
        jPanel1.add(btnIntern, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 320, 260, -1));

        panelImg.setBackground(new java.awt.Color(255, 255, 255));
        panelImg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        panelImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sidePanel.png"))); // NOI18N
        panelImg.setMaximumSize(new java.awt.Dimension(454, 707));
        panelImg.setMinimumSize(new java.awt.Dimension(454, 707));
        jPanel1.add(panelImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 715));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 715));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Appointment ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Patient Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Gender");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("status");

        txtPtName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtAptId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Date");

        btnGroupMF.add(rdbMale);
        rdbMale.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbMale.setText("Male");
        rdbMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbMaleActionPerformed(evt);
            }
        });

        btnGroupMF.add(rdbFemale);
        rdbFemale.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbFemale.setText("Female");

        rdbGroupFinAct.add(rdbAct);
        rdbAct.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbAct.setText("Active");

        rdbGroupFinAct.add(rdbFin);
        rdbFin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbFin.setText("Finished");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rdbMale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdbFemale))
                    .addComponent(txtPtName)
                    .addComponent(txtAptId)
                    .addComponent(txtDate)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rdbAct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(rdbFin)))
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtAptId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rdbMale)
                    .addComponent(rdbFemale))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rdbAct)
                    .addComponent(rdbFin))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 480, 280));

        txtRest.setBackground(new java.awt.Color(255, 255, 255));
        txtRest.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtRest.setText("Rest");
        txtRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRestActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnInsert.setBackground(new java.awt.Color(255, 255, 255));
        btnInsert.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnInsert.setText("Add");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(255, 255, 255));
        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnRest.setBackground(new java.awt.Color(255, 255, 255));
        btnRest.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRest.setText("Read");
        btnRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInsert, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRest, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRest, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit)
                .addGap(34, 34, 34))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, 120, 250));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Appointment management page");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed

        String aptId = txtAptId.getText();
        String patName = txtPtName.getText();
        
        String Gender ;
        if(rdbMale.isSelected())
            Gender = "Male";
        else
            Gender="Female";
        
        String date = txtDate.getText();
        String status ;
        if(rdbAct.isSelected())
            status = "Active";
        else
            status="Finished";
        
        try {
            
            stmt = con.createStatement();
            String sql = "INSERT INTO DB.APPINTMENT (APMTID, PATIENTNAME, GENDER, DATE, STATUS) \n" +
"	VALUES ("+aptId+", '"+patName+"', '"+Gender+"', '"+date+"', '"+status+"')";
        
        stmt.executeUpdate(sql);
        
        readData();
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }

        

    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestActionPerformed
        readData();
        
    }//GEN-LAST:event_btnRestActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked

        int row = tbl.getSelectedRow();
        // get appointment ID from table And set txt false
        txtAptId.setText(tbl.getValueAt(row, 0).toString());
        

        // get patient name from table And set txt false
        txtPtName.setText(tbl.getValueAt(row, 1).toString());
        

        String gender = tbl.getValueAt(row, 2).toString();
        
        if(gender.equalsIgnoreCase("Male")){
            rdbMale.setSelected(true);
        } else {
            rdbFemale.setSelected(true);
        }

        // get Date from table And set txt false
        txtDate.setText(tbl.getValueAt(row, 3).toString());
        

        String status = tbl.getValueAt(row, 4).toString();
        if(status.equalsIgnoreCase("Active")){
            rdbAct.setSelected(true);
        } else {
            rdbFin.setSelected(true);
        }

    }//GEN-LAST:event_tblMouseClicked

    private void btnPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientActionPerformed
       patient pt = new patient();
       pt.show();
       dispose();
    }//GEN-LAST:event_btnPatientActionPerformed

    private void btnApmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApmtActionPerformed
        Appointment ap = new Appointment();
        ap.show();
        dispose();
    }//GEN-LAST:event_btnApmtActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", 
        "Exit Clinic System", JOptionPane.YES_NO_OPTION);

        //  Check the user's choice
        if (response == JOptionPane.YES_OPTION) {
        System.exit(0); // Closes the program
}
    }//GEN-LAST:event_btnExitActionPerformed

    private void rdbMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbMaleActionPerformed

    private void txtRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRestActionPerformed
        
        txtAptId.setEditable(true);
     txtAptId.setText("");
    
    txtPtName.setEditable(true);
    txtPtName.setText("");
    
    txtDate.setEditable(true);
    txtDate.setText("");
    
    
    btnGroupMF.clearSelection(); 
    
    
    rdbGroupFinAct.clearSelection();
    
   
    //txtAptId.requestFocus(); No need for this
    }//GEN-LAST:event_txtRestActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
        try {
        
        Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/FinalProjectDB", "db", "123");

        
        String sql = "DELETE FROM DB.APPINTMENT WHERE apmtId = ?";
        PreparedStatement pst = con.prepareStatement(sql);

        
        pst.setInt(1, Integer.parseInt(txtAptId.getText()));

    
        pst.executeUpdate();
        btnRest.doClick(); 
        txtRest.doClick(); 

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try {
    Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/FinalProjectDB", "db", "123");
    
    // 1. Try with exact uppercase (Derby default)
    // Double check if your table is APPOINTMENT or APPINTMENT
    String sql = "SELECT * FROM DB.APPINTMENT WHERE APMTID = ?"; 
    
    PreparedStatement pst = con.prepareStatement(sql);
    pst.setString(1, txtSearch.getText().trim());
    
    res = pst.executeQuery(); 

    DefaultTableModel model = (DefaultTableModel) tbl.getModel();
    model.setRowCount(0); 

    if (res.next()) {
        // 2. Use column names EXACTLY as they appear in your database
        Object[] row = {
            res.getString("APMTID"),
            res.getString("PATIENTNAME"),
            res.getString("GENDER"),
            res.getString("DATE"), // Getting as String is safer for display
            res.getString("STATUS")
        };
        model.addRow(row);
    } else {
        JOptionPane.showMessageDialog(this, "No record found with that ID.");
    }
    

} catch (Exception e) {
    // This will tell us the EXACT error (like "Table not found")
    JOptionPane.showMessageDialog(this, e.getMessage());
}
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
                try {
            // Connect with DB
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/FinalProjectDB", "db", "123");
            String sql = "UPDATE DB.APPINTMENT SET patientName=?, Gender=?, date=?, status=? WHERE apmtId=?";
            PreparedStatement pst = con.prepareStatement(sql);

            // Fill DB
            pst.setString(1, txtPtName.getText());
            pst.setString(2, rdbMale.isSelected() ? "Male" : "Female");
            pst.setString(3, txtDate.getText()); // تمرير التاريخ كنص أسهل في Derby
            pst.setString(4, rdbAct.isSelected() ? "Active" : "Finished");
            pst.setInt(5, Integer.parseInt(txtAptId.getText()));

            // Execute and update db
            pst.executeUpdate();

            btnRest.doClick(); // لتحديث الجدول فوراً


        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,  e.getMessage());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnInternActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInternActionPerformed
        InternManagement intern = new InternManagement();
        intern.show();
        dispose();
    }//GEN-LAST:event_btnInternActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Appointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApmt;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.ButtonGroup btnGroupMF;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnIntern;
    private javax.swing.JButton btnPatient;
    private javax.swing.JButton btnRest;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel panelImg;
    private javax.swing.JRadioButton rdbAct;
    private javax.swing.JRadioButton rdbFemale;
    private javax.swing.JRadioButton rdbFin;
    private javax.swing.ButtonGroup rdbGroupFinAct;
    private javax.swing.JRadioButton rdbMale;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtAptId;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtPtName;
    private javax.swing.JButton txtRest;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
