/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ClinicSystem;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anas
 */
public class InternManagement extends javax.swing.JFrame {

    Connection con =null;
    Statement stmt = null;
    ResultSet res = null;
    
    
    /**
     * Creates new form InternManagement
     */
    public InternManagement() {
        initComponents();
        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/FinalProjectDB","db","123");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        
        
        //  Get the size of the PANEL, not the whole form
    int pWidth = internImg.getWidth();
    int pHeight = internImg.getHeight();

    //  Load your medical image
    ImageIcon icon = new ImageIcon(getClass().getResource("/Images/internImg.png"));

    //  Scale it to the PANEL's dimensions
    Image img = icon.getImage().getScaledInstance(pWidth, pHeight, Image.SCALE_SMOOTH);

    //  Apply it to the label and ensure the label fills the panel
    internImg.setIcon(new ImageIcon(img));
    internImg.setBounds(0, 0, pWidth, pHeight);
    
    
     //Exit btn design 
    btnExit.setBackground(new java.awt.Color(255, 102, 102)); // Modern soft red
    btnExit.setForeground(java.awt.Color.WHITE);
    btnExit.setFocusPainted(false);
    btnExit.setBorderPainted(false);
    
    
    // Search btn design
    btnSearch.setBackground(new java.awt.Color(0, 102, 204));
    btnSearch.setForeground(java.awt.Color.WHITE);
    
    //add btn design 
    btnAdd.setBackground(new Color(46, 204, 113));
    btnAdd.setForeground(Color.WHITE);
    btnAdd.setFont(new Font("Segoe UI", 1, 18));
    
    //delete btn design
    btnDelete.setFont(new Font("Segoe UI", 1, 18));
    btnDelete.setBackground(new Color(231, 76, 60));
    btnDelete.setForeground(Color.WHITE);
        
    }
    
    public void readData(){
    
        try {
         stmt = con.createStatement();
         res = stmt.executeQuery("SELECT * FROM DB.INTERNSHIP");
    
        // 1. Get the Model and CLEAR it first so you don't get duplicates
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        model.setRowCount(0); 
    
        while (res.next()) {
           // 2. Get data from the database
           int id = res.getInt("id");
           String name = res.getString("name");
           String university = res.getString("university");
           int cridetHours = res.getInt("creditHours");
           

           // 3. Add a NEW row to the table with the data
           model.addRow(new Object[]{id,name, university, cridetHours});
       }
    
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSearch = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnPatient = new javax.swing.JButton();
        btnAppointment = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        internImg = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtUni = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHours = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnRead = new javax.swing.JButton();
        btnRest = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 260, -1));

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 260, -1));

        txtSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 260, -1));

        btnPatient.setBackground(new java.awt.Color(255, 255, 255));
        btnPatient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPatient.setText("Patient");
        btnPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientActionPerformed(evt);
            }
        });
        getContentPane().add(btnPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 310, 260, -1));

        btnAppointment.setBackground(new java.awt.Color(255, 255, 255));
        btnAppointment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAppointment.setText("Appintment");
        btnAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppointmentActionPerformed(evt);
            }
        });
        getContentPane().add(btnAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 260, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("InternShip");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 260, -1));

        internImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/internImg.png"))); // NOI18N
        getContentPane().add(internImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 260, 710));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Intern ID");

        txtId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Name");

        txtUni.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("University");

        txtHours.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Credit hours");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHours)
                    .addComponent(txtId)
                    .addComponent(txtName)
                    .addComponent(txtUni, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 430, 190));

        btnRead.setBackground(new java.awt.Color(255, 255, 255));
        btnRead.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRead.setText("Read");
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });

        btnRest.setBackground(new java.awt.Color(255, 255, 255));
        btnRest.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRest.setText("Rest");
        btnRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(255, 255, 255));
        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRead)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 90, 110, 200));

        tbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "University", "Credit hours"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 590, 300));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Interns management");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestActionPerformed

        txtId.setEditable(true);
        txtId.setText("");
    
        txtName.setEditable(true);
        txtName.setText("");

        txtUni.setEditable(true);
        txtUni.setText("");
    
        txtHours.setEditable(true);
        txtHours.setText("");
        
    }//GEN-LAST:event_btnRestActionPerformed

    private void btnPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientActionPerformed
        patient pt = new patient();
       pt.show();
       dispose();
    }//GEN-LAST:event_btnPatientActionPerformed

    private void btnAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppointmentActionPerformed
       Appointment ap = new Appointment();
        ap.show();
        dispose();
    }//GEN-LAST:event_btnAppointmentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       InternManagement intern = new InternManagement();
       intern.show();
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
        readData();
    }//GEN-LAST:event_btnReadActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
         int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", 
        "Exit Clinic System", JOptionPane.YES_NO_OPTION);

        //  Check the user's choice
        if (response == JOptionPane.YES_OPTION) {
        System.exit(0); // Closes the program
        }
        
        
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        String id = txtId.getText();
        String name = txtName.getText();
        String uni = txtUni.getText();
        String CHour = txtHours.getText();
        
        
        try {
            
            stmt = con.createStatement();
            String sql = "INSERT INTO DB.INTERNSHIP (ID, NAME, UNIVERSITY, CREDITHOURS) \n" +
"	VALUES ("+id+", '"+name+"', '"+uni+"', "+CHour+")";
        
        stmt.executeUpdate(sql);
        
        readData();
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }

        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
        try {
        
        Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/FinalProjectDB", "db", "123");

        
        String sql = "DELETE FROM DB.INTERNSHIP WHERE ID = ?";
        PreparedStatement pst = con.prepareStatement(sql);

        
        pst.setInt(1, Integer.parseInt(txtId.getText()));

    
        pst.executeUpdate();
        btnRead.doClick(); 
        btnRest.doClick(); 

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        
    try {
        Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/FinalProjectDB", "db", "123");

        // The order here is: 1.Name, 2.University, 3.Hours, 4.ID
        String sql = "UPDATE DB.INTERNSHIP SET NAME=?, UNIVERSITY=?, CREDITHOURS=? WHERE ID=?";
        PreparedStatement pst = con.prepareStatement(sql);

        // MATCH THE NUMBERS TO THE SQL STRING ABOVE:
        pst.setString(1, txtName.getText());  // 1st ? is NAME
        pst.setString(2, txtUni.getText());   // 2nd ? is UNIVERSITY
        pst.setString(3, txtHours.getText()); // 3rd ? is CREDITHOURS
        pst.setString(4, txtId.getText());    // 4th ? is the ID in WHERE clause

        pst.executeUpdate();


        btnRead.doClick(); // Use Read to refresh the table, not Rest
    
   
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        
        int row = tbl.getSelectedRow();
        
        
        txtId.setText(tbl.getValueAt(row, 0).toString());
        txtName.setText(tbl.getValueAt(row, 1).toString());
        txtUni.setText(tbl.getValueAt(row, 2).toString());
        txtHours.setText(tbl.getValueAt(row, 3).toString());
        
    }//GEN-LAST:event_tblMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        
        try {
    Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/FinalProjectDB", "db", "123");
    
    // 1. Try with exact uppercase (Derby default)
    // Double check if your table is APPOINTMENT or APPINTMENT
    String sql = "SELECT * FROM DB.INTERNSHIP WHERE ID = ?"; 
    
    PreparedStatement pst = con.prepareStatement(sql);
    pst.setString(1, txtSearch.getText().trim());
    
    res = pst.executeQuery(); 

    DefaultTableModel model = (DefaultTableModel) tbl.getModel();
    model.setRowCount(0); 

    if (res.next()) {
        // 2. Use column names EXACTLY as they appear in your database
        Object[] row = {
            res.getString("ID"),
            res.getString("NAME"),
            res.getString("UNIVERSITY"),
            res.getString("CREDITHOURS"),
            
        };
        model.addRow(row);
    } else {
        JOptionPane.showMessageDialog(this, "No record found with that ID.");
    }
    

} catch (Exception e) {
    // This will tell us the EXACT error (like "Table not found")
    JOptionPane.showMessageDialog(this, e.getMessage());
}
        
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InternManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InternManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InternManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InternManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InternManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAppointment;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPatient;
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnRest;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel internImg;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtHours;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtUni;
    // End of variables declaration//GEN-END:variables
}
