/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ClinicSystem;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anas
 */
public class patient extends javax.swing.JFrame {

    Connection con = null;
    Statement stmt = null;
    ResultSet res = null; 
    /**
     * Creates new form patient
     */
    public patient() {
        initComponents();
        
        try {
            
      con = DriverManager.getConnection("jdbc:derby://localhost:1527/FinalProjectDB","db","123");
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
         //  Get the size of the PANEL, not the whole form
    int pWidth = panelImg.getWidth();
    int pHeight = panelImg.getHeight();

    //  Load your medical image
    ImageIcon icon = new ImageIcon(getClass().getResource("/Images/sidePanel.png"));

    //  Scale it to the PANEL's dimensions
    Image img = icon.getImage().getScaledInstance(pWidth, pHeight, Image.SCALE_SMOOTH);

    //  Apply it to the label and ensure the label fills the panel
    panelImg.setIcon(new ImageIcon(img));
    panelImg.setBounds(0, 0, pWidth, pHeight);
    
    
    //Exit btn design 
    btnExit.setBackground(new java.awt.Color(255, 102, 102)); // Modern soft red
    btnExit.setForeground(java.awt.Color.WHITE);
    btnExit.setFocusPainted(false);
    btnExit.setBorderPainted(false);
    
    
    // Search btn design
    btnSearch.setBackground(new java.awt.Color(0, 102, 204));
    btnSearch.setForeground(java.awt.Color.WHITE);
    
    //add btn design 
    btnAdd.setBackground(new Color(46, 204, 113));
    btnAdd.setForeground(Color.WHITE);
    btnAdd.setFont(new Font("Segoe UI", 1, 18));
    
    //delete btn design
    btnDelete.setFont(new Font("Segoe UI", 1, 18));
    btnDelete.setBackground(new Color(231, 76, 60));
    btnDelete.setForeground(Color.WHITE);
    
    }
    
    public void readData(){
    
        try {
         stmt = con.createStatement();
         res = stmt.executeQuery("SELECT * FROM DB.PATIENT");
    
        // 1. Get the Model and CLEAR it first so you don't get duplicates
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        model.setRowCount(0); 
    
        while (res.next()) {
           // 2. Get data from the database
           int patId = res.getInt("patId");
           String patName = res.getString("patName");
           int age = res.getInt("age");
           int phone = res.getInt("phone");
           

           // 3. Add a NEW row to the table with the data
           model.addRow(new Object[]{patId, patName, age, phone});
       }
    
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnApmt = new javax.swing.JButton();
        btnPatient = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panelImg = new javax.swing.JLabel();
        btnRead = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnRest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnApmt.setBackground(new java.awt.Color(255, 255, 255));
        btnApmt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnApmt.setText("Appointment");
        btnApmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApmtActionPerformed(evt);
            }
        });
        getContentPane().add(btnApmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 260, -1));

        btnPatient.setBackground(new java.awt.Color(255, 255, 255));
        btnPatient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPatient.setText("Patient");
        getContentPane().add(btnPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 260, -1));

        txtSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 260, -1));

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 260, -1));

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 260, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("InternShip ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 260, -1));

        panelImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sidePanel.png"))); // NOI18N
        panelImg.setMaximumSize(new java.awt.Dimension(454, 707));
        panelImg.setMinimumSize(new java.awt.Dimension(454, 707));
        getContentPane().add(panelImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 760));

        btnRead.setBackground(new java.awt.Color(255, 255, 255));
        btnRead.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRead.setText("Read");
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });
        getContentPane().add(btnRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 140, 100, 40));

        tbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Age", "Phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 735, 380));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Patient Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Age");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Phone");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        txtId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 260, -1));

        txtAge.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 260, -1));

        txtName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 260, -1));

        txtPhone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 260, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Patient ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Patient Management Page");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 330, 30));

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 240, 100, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 290, 100, 40));

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, 100, 40));

        btnRest.setBackground(new java.awt.Color(255, 255, 255));
        btnRest.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRest.setText("Rest");
        btnRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestActionPerformed(evt);
            }
        });
        getContentPane().add(btnRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 190, 100, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed

        readData();
    }//GEN-LAST:event_btnReadActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        
        int row = tbl.getSelectedRow();
        
        
        txtId.setText(tbl.getValueAt(row, 0).toString());
        txtName.setText(tbl.getValueAt(row, 1).toString());
        txtAge.setText(tbl.getValueAt(row, 2).toString());
        txtPhone.setText(tbl.getValueAt(row, 3).toString());
        
    }//GEN-LAST:event_tblMouseClicked

    private void btnApmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApmtActionPerformed
        
        Appointment ap = new Appointment();
        ap.show();
        dispose();
        
    }//GEN-LAST:event_btnApmtActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", 
        "Exit Clinic System", JOptionPane.YES_NO_OPTION);

        //  Check the user's choice
        if (response == JOptionPane.YES_OPTION) {
        System.exit(0); // Closes the program
        }
        
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try {
    Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/FinalProjectDB", "db", "123");
    
    // 1. Try with exact uppercase (Derby default)
    // Double check if your table is APPOINTMENT or APPINTMENT
    String sql = "SELECT * FROM DB.PATIENT WHERE PATID = ?"; 
    
    PreparedStatement pst = con.prepareStatement(sql);
    pst.setString(1, txtSearch.getText().trim());
    
    res = pst.executeQuery(); 

    DefaultTableModel model = (DefaultTableModel) tbl.getModel();
    model.setRowCount(0); 

    if (res.next()) {
        // 2. Use column names EXACTLY as they appear in your database
        Object[] row = {
            res.getString("patId"),
            res.getString("patName"),
            res.getString("age"),
            res.getString("phone"), // Getting as String is safer for display
            
        };
        model.addRow(row);
    } else {
        JOptionPane.showMessageDialog(this, "No record found with that ID.");
    }
    

} catch (Exception e) {
    
    JOptionPane.showMessageDialog(this, e.getMessage());
}
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        String id = txtId.getText();
        String name = txtName.getText();
        String age = txtAge.getText();
        String phone = txtPhone.getText();
        
        
        try {
            
            stmt = con.createStatement();
            String sql = "INSERT INTO DB.PATIENT (PATID, PATNAME, AGE, PHONE) \n" +
"	VALUES ("+id+", '"+name+"', "+age+", "+phone+")";
        
        stmt.executeUpdate(sql);
        
        readData();
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestActionPerformed
        
        txtId.setEditable(true);
        txtId.setText("");
    
        txtName.setEditable(true);
        txtName.setText("");

        txtAge.setEditable(true);
        txtAge.setText("");
    
        txtPhone.setEditable(true);
        txtPhone.setText("");
     
    
    }//GEN-LAST:event_btnRestActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        InternManagement intern = new InternManagement();
        intern.show();
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
        try {
        
        Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/FinalProjectDB", "db", "123");

        
        String sql = "DELETE FROM DB.PATIENT WHERE PATID = ?";
        PreparedStatement pst = con.prepareStatement(sql);

        
        pst.setInt(1, Integer.parseInt(txtId.getText()));

    
        pst.executeUpdate();
        btnRead.doClick(); 
        btnRest.doClick(); 

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try {
    Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/FinalProjectDB", "db", "123");
    
    // The order here is: 1.Name, 2.University, 3.Hours, 4.ID
    String sql = "UPDATE DB.PATIENT SET PATNAME=?, AGE=?, PHONE=? WHERE PATID=?";
    PreparedStatement pst = con.prepareStatement(sql);

    // MATCH THE NUMBERS TO THE SQL STRING ABOVE:
    pst.setString(1, txtName.getText());  // 1st ? is NAME
    pst.setString(2, txtAge.getText());   // 2nd ? is UNIVERSITY
    pst.setString(3, txtPhone.getText()); // 3rd ? is CREDITHOURS
    pst.setString(4, txtId.getText());    // 4th ? is the ID in WHERE clause

    pst.executeUpdate();
    

    btnRead.doClick(); // Use Read to refresh the table, not Rest
    
   
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, e.getMessage());
}
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnApmt;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPatient;
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnRest;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel panelImg;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
